#!/bin/bash

docker network create rebase-labs

docker-compose run \
  --rm \
  -d \
  --name redis \
  redis

docker-compose run \
  --rm \
  -d \
  --name redis-worker \
  app \
  bash -c "bundle install && sidekiq -r ./lib/importer.rb"

docker-compose run \
  --rm \
  -d \
  --name pgserver \
  pgserver

docker-compose run \
  --rm \
  --name rebase-labs \
  --service-ports \
  app \
  bash -c "bundle install && ruby server.rb"

docker stop pgserver
docker stop redis-worker
docker stop redis
docker rm redis-worker
docker rm redis
docker rm pgserver